---
- name: Workflow 2 Job Template Playbook 1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for 2 seconds task
      ansible.builtin.wait_for:
        timeout: 2

    - name: Print in to ansible log using debug module "Job template 1 Done"
      ansible.builtin.debug:
        msg: "Job template 1 Done"
