---
- name: Workflow 4 App1 Lock
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for 30 seconds task
      ansible.builtin.wait_for:
        timeout: 50

    - name: Print in to ansible log using debug module "Job template 1 Done"
      ansible.builtin.debug:
        msg: "App1 Done"
