---
- name: Workflow 1 Job Template Playbook 2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for 2 seconds task
      ansible.builtin.wait_for:
        timeout: 2

    - name: Print in to ansible log using debug module "Job template 2 Done"
      ansible.builtin.debug:
        msg: "Job template 2 Done"
